CXX := g++
FLAGS := -O3

all:
	$(CXX) $(FLAGS) find_a_cat_v1.cpp -o find_a_cat_v1
	$(CXX) $(FLAGS) find_a_cat_v2.cpp -o find_a_cat_v2
	$(CXX) $(FLAGS) prove_xorshift.cpp -o prove_xorshift
clean:
	$(RM) find_a_cat_v1 find_a_cat_v2 prove_xorshift
